grails-app/controllers/com/eximiomedia/NewsController.groovy
package com.eximiomedia



import static org.springframework.http.HttpStatus.*
import com.notnoop.apns.APNS
import com.notnoop.apns.ApnsNotification
import com.notnoop.apns.ApnsService
import com.google.android.gcm.server.Message
import grails.transaction.Transactional
import grails.plugin.springsecurity.annotation.Secured

@Secured(['ROLE_ADMIN'])
@Transactional(readOnly = true)
class NewsController {

	static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

	def androidGcmService

	ApnsService apnsService

	def index(Integer max) {
		params.max = Math.min(max ?: 10, 100)
		respond News.list(params), model:[newsInstanceCount: News.count()]
	}

	def show(News newsInstance) {
		respond newsInstance
	}

	def create() {
		respond new News(params)
	}

	@Transactional
	def save(News newsInstance) {
		if (newsInstance == null) {
			notFound()
			return
		}

		if (newsInstance.hasErrors()) {
			respond newsInstance.errors, view:'create'
			return
		}

		newsInstance.save flush:true

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.created.message', args: [
					message(code: 'newsInstance.label', default: 'News'),
					newsInstance.id
				])
				redirect newsInstance
			}
			'*' { respond newsInstance, [status: CREATED] }
		}
	}

	def edit(News newsInstance) {
		respond newsInstance
	}

	def sendNotif(News newsInstance) {
		//def appUser = AppUser.list()
		def appUser = AppUser.findAllByNama("Ujang Anom")

		Map msg = new HashMap()
		msg.put("message",newsInstance.id.toString())
		msg.put("title",newsInstance.newsTitle)
		msg.put("msgcnt","6")

		List devices = new ArrayList()

		appUser.each { u ->
			if(u.regid) {
				devices.add(u.regid)
			}
		}

		def part = partition(devices,999)

		for(i in 0..part.size()-1) {
			androidGcmService.sendMessage(msg, part[i])
		}

		/*def regs = PushRegistration.list()

		List regdevs = new ArrayList()

		regs.each { r ->
			if(r.regid) {
				regdevs.add(r.regid)
			}
		}

		def rpart = partition(regdevs,999)

		for(i in 0..rpart.size()-1) {
			androidGcmService.sendMessage(msg, rpart[i])
		}*/
		
		respond newsInstance, view:"show"
	}

	@Transactional
	def update(News newsInstance) {
		if (newsInstance == null) {
			notFound()
			return
		}

		if (newsInstance.hasErrors()) {
			respond newsInstance.errors, view:'edit'
			return
		}

		newsInstance.save flush:true

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.updated.message', args: [
					message(code: 'News.label', default: 'News'),
					newsInstance.id
				])
				redirect newsInstance
			}
			'*'{ respond newsInstance, [status: OK] }
		}
	}

	@Transactional
	def delete(News newsInstance) {

		if (newsInstance == null) {
			notFound()
			return
		}

		newsInstance.delete flush:true

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.deleted.message', args: [
					message(code: 'News.label', default: 'News'),
					newsInstance.id
				])
				redirect action:"index", method:"GET"
			}
			'*'{ render status: NO_CONTENT }
		}
	}

	protected void notFound() {
		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.not.found.message', args: [
					message(code: 'newsInstance.label', default: 'News'),
					params.id
				])
				redirect action: "index", method: "GET"
			}
			'*'{ render status: NOT_FOUND }
		}
	}
	
	def partition(array, size) {
		def partitions = []
		int partitionCount = array.size() / size

		partitionCount.times { partitionNumber ->
			def start = partitionNumber * size
			def end = start + size - 1
			partitions << array[start..end]
		}

		if (array.size() % size) partitions << array[partitionCount * size..-1]
		return partitions
	}
}

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title><g:layoutTitle default="Grails" /></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon"
	href="${resource(dir: 'images', file: 'favicon.ico')}"
	type="image/x-icon">
<link rel="apple-touch-icon"
	href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
<link rel="apple-touch-icon" sizes="114x114"
	href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
<link rel="stylesheet"
	href="${resource(dir: 'font-awesome/css', file: 'font-awesome.min.css')}"
	type="text/css">	
<link rel="stylesheet"
	href="${resource(dir: 'assets/css', file: 'style.css')}"
	type="text/css">
<g:javascript library="jquery" />
<r:require module="jquery-ui" />
<ckeditor:resources />
<g:javascript library="template" />
<r:require module="export" />
<export:resource />
<g:layoutHead />
<g:javascript library="application" />
<r:layoutResources />
</head>
<body>
	<div class="header">
		<div class="left">
			<sec:ifAnyGranted roles="ROLE_ADMIN">
				<div class="icon title" onclick="adminhome()"></div>
			</sec:ifAnyGranted>
			<sec:ifAnyGranted roles="ROLE_DOCTOR">
				<div class="icon title" onclick="doctorhome()"></div>
			</sec:ifAnyGranted>
		</div>
		<sec:ifLoggedIn>
			<div class="right">
				<div class="navbar-right">
					<span class="icon username"></span> <span class="text"><sec:loggedInUserInfo
							field="fullname"></sec:loggedInUserInfo></span> <span class="divider"></span>
					<span style="clear: both"></span>
				</div>
				<div class="navbar-right btn-logout" onclick="logout()">
					<span class="icon logout"></span> <span class="text">Log out</span>
					<span class="divider"></span> <span style="clear: both"></span>
				</div>
			</div>
		</sec:ifLoggedIn>
	</div>
	<div class="container" id="maincont">
		<sec:ifLoggedIn>
			<div class="leftbar">
				<div class="menu">
					<sec:ifAnyGranted roles="ROLE_DOCTOR">
						<div class="sidebar-chat">
							<g:link controller="doctor" action="chat">
								<span class="notif" id="chatnotif"></span>
								<span class="icon image"></span>
								<span class="text">Chat</span>
							</g:link>
						</div>
						<div class="sidebar-message">
							<g:link controller="question">
								<div class="notif" id="msgnotif"></div>
								<div class="icon image"></div>
								<div class="text">Pesan</div>
							</g:link>
						</div>
					</sec:ifAnyGranted>
					<sec:ifAnyGranted roles="ROLE_ADMIN">
						<div class="sidebar-article">
							<g:link controller="article" action="index">
								<div class="text"><i class="fa fa-file-text-o"></i>&nbsp;&nbsp;Article</div>
							</g:link>
						</div>
						<div class="sidebar-myth mitfak">
							<g:link controller="mitosfakta" action="index">
								<div class="text"><i class="fa fa-eye-slash"></i>&nbsp;Myth&Fact</div>
							</g:link>
						</div>
						<div class="sidebar-myth cal">
							<g:link controller="calorie" action="index">
								<div class="text"><i class="fa fa-cutlery"></i>&nbsp;&nbsp;Calorie</div>
							</g:link>
						</div>
						<div class="sidebar-myth sched">
							<g:link controller="chatSchedule" action="index">
								<div class="text"><i class="fa fa-calendar"></i>&nbsp;&nbsp;Schedule</div>
							</g:link>
						</div>
						<div class="sidebar-myth quest">
							<g:link controller="question" action="adminquestion">
								<div class="text"><i class="fa fa-question-circle"></i>&nbsp;&nbsp;Questions</div>
							</g:link>
						</div>
						<div class="sidebar-myth news">
							<g:link controller="news" action="index">
								<div class="text"><i class="fa fa-newspaper-o"></i> News</div>
							</g:link>
						</div>
						<div class="sidebar-myth doctor">
							<g:link controller="user" action="index">
								<div class="text"><i class="fa fa-user"></i>&nbsp;&nbsp;&nbsp;Doctor</div>
							</g:link>
						</div>
						<div class="sidebar-myth stat">
							<g:link controller="statistic">
								<div class="text"><i class="fa fa-bar-chart"></i> Statistic</div>
							</g:link>
						</div>
					</sec:ifAnyGranted>
				</div>
			</div>
		</sec:ifLoggedIn>
		<div class="content">
			<g:layoutBody />
		</div>
	</div>
	<script>
		function logout() {
			window.location.href = '${createLink(controller: "logout")}';
		}

		function adminhome() {
			window.location.href = '${createLink(controller: "admin")}';
		}

		function doctorhome() {
			window.location.href = '${createLink(controller: "doctor")}';
		}

		$(function() {
			var pathArray = window.location.pathname.split('/');
			if (pathArray[3] == "chat") {
				$(".sidebar-chat.sidebar-message.sidebar-article.sidebar-myth")
						.removeClass("active");
				$(".sidebar-chat").addClass("active");
			}
			if (pathArray[2] == "question") {
				$(".sidebar-chat.sidebar-message.sidebar-article.sidebar-myth")
						.removeClass("active");
				$(".sidebar-message").addClass("active");
			}
			if (pathArray[2] == "article") {
				$(".sidebar-chat.sidebar-message.sidebar-article.sidebar-myth")
						.removeClass("active");
				$(".sidebar-article").addClass("active");
			}
			if (pathArray[2] == "mitosfakta") {
				$(".sidebar-chat.sidebar-message.sidebar-article.sidebar-myth")
						.removeClass("active");
				$(".mitfak").addClass("active");
			}
			if (pathArray[2] == "calorie") {
				$(".sidebar-chat.sidebar-message.sidebar-article.sidebar-myth")
						.removeClass("active");
				$(".cal").addClass("active");
			}
			if (pathArray[2] == "chatSchedule") {
				$(".sidebar-chat.sidebar-message.sidebar-article.sidebar-myth")
						.removeClass("active");
				$(".sched").addClass("active");
			}
			if (pathArray[2] == "question") {
				$(".sidebar-chat.sidebar-message.sidebar-article.sidebar-myth")
						.removeClass("active");
				$(".quest").addClass("active");
			}
			if (pathArray[2] == "news") {
				$(".sidebar-chat.sidebar-message.sidebar-article.sidebar-myth")
						.removeClass("active");
				$(".news").addClass("active");
			}
			if (pathArray[2] == "user") {
				$(".sidebar-chat.sidebar-message.sidebar-article.sidebar-myth")
						.removeClass("active");
				$(".doctor").addClass("active");
			}
			if (pathArray[2] == "statistic") {
				$(".sidebar-chat.sidebar-message.sidebar-article.sidebar-myth")
						.removeClass("active");
				$(".stat").addClass("active");
			}
		});
	</script>
	<r:layoutResources />
</body>
</html>