grails-app/domain/com/eximiomedia/ChatSchedule.groovy
package com.eximiomedia

import com.eximiomedia.auth.User

class ChatSchedule {
	
	User dokter
	String day
	String startTime
	String endTime

    static constraints = {
    }
}

grails-app/controllers/com/eximiomedia/ChatScheduleController.groovy
package com.eximiomedia



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import grails.plugin.springsecurity.annotation.Secured

@Secured(['ROLE_ADMIN'])
@Transactional(readOnly = true)
class ChatScheduleController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond ChatSchedule.list(params), model:[chatScheduleInstanceCount: ChatSchedule.count()]
    }

    def show(ChatSchedule chatScheduleInstance) {
        respond chatScheduleInstance
    }

    def create() {
        respond new ChatSchedule(params)
    }

    @Transactional
    def save(ChatSchedule chatScheduleInstance) {
        if (chatScheduleInstance == null) {
            notFound()
            return
        }

        if (chatScheduleInstance.hasErrors()) {
            respond chatScheduleInstance.errors, view:'create'
            return
        }

        chatScheduleInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'chatScheduleInstance.label', default: 'ChatSchedule'), chatScheduleInstance.id])
                redirect chatScheduleInstance
            }
            '*' { respond chatScheduleInstance, [status: CREATED] }
        }
    }

    def edit(ChatSchedule chatScheduleInstance) {
        respond chatScheduleInstance
    }

    @Transactional
    def update(ChatSchedule chatScheduleInstance) {
        if (chatScheduleInstance == null) {
            notFound()
            return
        }

        if (chatScheduleInstance.hasErrors()) {
            respond chatScheduleInstance.errors, view:'edit'
            return
        }

        chatScheduleInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'ChatSchedule.label', default: 'ChatSchedule'), chatScheduleInstance.id])
                redirect chatScheduleInstance
            }
            '*'{ respond chatScheduleInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(ChatSchedule chatScheduleInstance) {

        if (chatScheduleInstance == null) {
            notFound()
            return
        }

        chatScheduleInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'ChatSchedule.label', default: 'ChatSchedule'), chatScheduleInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'chatScheduleInstance.label', default: 'ChatSchedule'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/chatSchedule/_form.gsp
<%@ page import="com.eximiomedia.ChatSchedule" %>

<div class="fieldcontain ${hasErrors(bean: chatScheduleInstance, field: 'dokter', 'error')} ">
	<label for="dokter">
		<g:message code="chatSchedule.dokter.label" default="Dokter" />
		
	</label>
	<g:select id="dokter" name="dokter.id" from="${com.eximiomedia.auth.UserAuthority.findAllByAuthority(com.eximiomedia.auth.Authority.findByAuthority("ROLE_DOCTOR")).user}" optionKey="id" required="" value="${chatScheduleInstance?.dokter?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: chatScheduleInstance, field: 'day', 'error')} ">
	<label for="day">
		<g:message code="chatSchedule.day.label" default="Day" />
		
	</label>
	<g:select name="day" from="${['Minggu','Senin','Selasa','Rabu','Kamis','Jum\'at','Sabtu']}" value="${chatScheduleInstance?.day}" />

</div>


<div class="fieldcontain ${hasErrors(bean: chatScheduleInstance, field: 'startTime', 'error')} ">
	<label for="startTime">
		<g:message code="chatSchedule.startTime.label" default="Start Time" />
		
	</label>
	<g:textField name="startTime" value="${chatScheduleInstance?.startTime}" />

</div>

<div class="fieldcontain ${hasErrors(bean: chatScheduleInstance, field: 'endTime', 'error')} ">
	<label for="endTime">
		<g:message code="chatSchedule.endTime.label" default="End Time" />
		
	</label>
	<g:textField name="endTime" value="${chatScheduleInstance?.endTime}" />

</div>

grails-app/views/chatSchedule/create.gsp
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'chatSchedule.label', default: 'ChatSchedule')}" />
<title><g:message code="default.create.label"
		args="[entityName]" /></title>
</head>
<body>
	<div class="article-add">
		<div class="nav nav-article">
			<div class="left">
				<span class="icon"></span> <span class="text"
					onclick="window.history.back()">List Schedule</span>
			</div>
			<div class="right">
				<div class="btn-blue cursor">
					<span class="icon"></span>
					<g:link action="create">
						<span class="text">add new article</span>
					</g:link>
				</div>
			</div>
		</div>
		<g:if test="${flash.message}">
			<div class="message" role="status">
				${flash.message}
			</div>
		</g:if>
		<g:hasErrors bean="${chatScheduleInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${chatScheduleInstance}" var="error">
					<li
						<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
							error="${error}" /></li>
				</g:eachError>
			</ul>
		</g:hasErrors>
		<g:form url="[resource:chatScheduleInstance, action:'save']">
			<fieldset class="form">
				<g:render template="form" />
			</fieldset>
			<fieldset class="buttons">
				<g:submitButton name="create" class="save"
					value="${message(code: 'default.button.create.label', default: 'Create')}" />
			</fieldset>
		</g:form>
	</div>
</body>
</html>

grails-app/views/chatSchedule/edit.gsp
<%@ page import="com.eximiomedia.ChatSchedule"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'chatSchedule.label', default: 'ChatSchedule')}" />
<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
	<div class="myth-add">
		<div class="nav nav-myth">
			<div class="left">
				<span class="icon"></span> <span class="text"
					onclick="window.history.back()">List Schedule</span>
			</div>
			<div class="right">
				<div class="btn-blue cursor">
					<span class="icon"></span>
					<g:link action="create">
						<span class="text">add new calorie</span>
					</g:link>
				</div>
			</div>
		</div>
		<g:if test="${flash.message}">
			<div class="message" role="status">
				${flash.message}
			</div>
		</g:if>
		<g:hasErrors bean="${chatScheduleInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${chatScheduleInstance}" var="error">
					<li
						<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
							error="${error}" /></li>
				</g:eachError>
			</ul>
		</g:hasErrors>
		<g:form url="[resource:chatScheduleInstance, action:'update']"
			method="PUT">
			<g:hiddenField name="version"
				value="${chatScheduleInstance?.version}" />
			<fieldset class="form">
				<g:render template="form" />
			</fieldset>
			<fieldset class="buttons">
				<g:actionSubmit class="save" action="update"
					value="${message(code: 'default.button.update.label', default: 'Update')}" />
			</fieldset>
		</g:form>
	</div>
</body>
</html>

grails-app/views/chatSchedule/index.gsp
<%@ page import="com.eximiomedia.ChatSchedule"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'chatSchedule.label', default: 'ChatSchedule')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
	<div class="myth-list">
		<div class="nav nav-myth">
			<div class="left">
				<span class="text">List Schedule Chat</span>
			</div>
			<div class="right">
				<div class="btn-blue cursor">
					<span class="icon"></span>
					<g:link action="create">
						<span class="text">add new schedule</span>
					</g:link>
				</div>
			</div>
		</div>
		<g:if test="${flash.message}">
			<div class="message" role="status">
				${flash.message}
			</div>
		</g:if>
		<div class="lists">
			<div class="list-item">
				<table>
					<thead>
						<tr>



							<th><g:message code="chatSchedule.dokter.label"
									default="Dokter" /></th>

							<g:sortableColumn property="day"
								title="${message(code: 'chatSchedule.day.label', default: 'Day')}" />

							<g:sortableColumn property="startTime"
								title="${message(code: 'chatSchedule.startTime.label', default: 'Start Time')}" />

							<g:sortableColumn property="endTime"
								title="${message(code: 'chatSchedule.endTime.label', default: 'End Time')}" />



							<th>Action</th>

						</tr>
					</thead>
					<tbody>
						<g:each in="${chatScheduleInstanceList}" status="i"
							var="chatScheduleInstance">
							<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

								<td><g:link action="show" id="${chatScheduleInstance.id}">
										${fieldValue(bean: chatScheduleInstance, field: "dokter")}
									</g:link></td>

								<td>
									${fieldValue(bean: chatScheduleInstance, field: "day")}
								</td>
								<td>
									${fieldValue(bean: chatScheduleInstance, field: "startTime")}
								</td>


								<td>
									${fieldValue(bean: chatScheduleInstance, field: "endTime")}
								</td>



								<td><g:form
										url="[resource:chatScheduleInstance, action:'delete']"
										method="DELETE">
										<g:link class="edit" action="edit"
											resource="${chatScheduleInstance}">
											<g:message code="default.button.edit.label" default="Edit" />
										</g:link>
										<g:actionSubmit class="delete" action="delete"
											value="${message(code: 'default.button.delete.label', default: 'Delete')}"
											onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
									</g:form></td>

							</tr>
						</g:each>
					</tbody>
				</table>
			</div>
		</div>
		<div class="pagination">
			<g:paginate total="${chatScheduleInstanceCount ?: 0}" />
		</div>
	</div>
</body>
</html>

grails-app/views/chatSchedule/show.gsp
<%@ page import="com.eximiomedia.ChatSchedule" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'chatSchedule.label', default: 'ChatSchedule')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="myth-add">
			<div class="nav nav-myth">
				<div class="left">
					<span class="icon"></span> <span class="text"
						onclick="window.history.back()">Back</span>
				</div>
				<div class="right">
					<div class="btn-blue cursor">
						<span class="icon"></span>
						<g:link action="create">
							<span class="text">add new schedule</span>
						</g:link>
					</div>
				</div>
			</div>
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list chatSchedule">
			
				<g:if test="${chatScheduleInstance?.day}">
				<li class="fieldcontain">
					<span id="day-label" class="property-label"><g:message code="chatSchedule.day.label" default="Day" /></span>
					
						<span class="property-value" aria-labelledby="day-label"><g:fieldValue bean="${chatScheduleInstance}" field="day"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${chatScheduleInstance?.dokter}">
				<li class="fieldcontain">
					<span id="dokter-label" class="property-label"><g:message code="chatSchedule.dokter.label" default="Dokter" /></span>
					
						<span class="property-value" aria-labelledby="dokter-label"><g:link controller="user" action="show" id="${chatScheduleInstance?.dokter?.id}">${chatScheduleInstance?.dokter?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${chatScheduleInstance?.endTime}">
				<li class="fieldcontain">
					<span id="endTime-label" class="property-label"><g:message code="chatSchedule.endTime.label" default="End Time" /></span>
					
						<span class="property-value" aria-labelledby="endTime-label"><g:fieldValue bean="${chatScheduleInstance}" field="endTime"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${chatScheduleInstance?.startTime}">
				<li class="fieldcontain">
					<span id="startTime-label" class="property-label"><g:message code="chatSchedule.startTime.label" default="Start Time" /></span>
					
						<span class="property-value" aria-labelledby="startTime-label"><g:fieldValue bean="${chatScheduleInstance}" field="startTime"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:chatScheduleInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${chatScheduleInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>