grails-app/domain/com/eximiomedia/AppVersion.groovy
package com.eximiomedia

class AppVersion {
	
	String appversion

    static constraints = {
    }
}

grails-app/controllers/com/eximiomedia/AppVersionController.groovy
package com.eximiomedia



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import grails.plugin.springsecurity.annotation.Secured

@Secured(['ROLE_ADMIN'])
@Transactional(readOnly = true)
class AppVersionController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond AppVersion.list(params), model:[appVersionInstanceCount: AppVersion.count()]
    }

    def show(AppVersion appVersionInstance) {
        respond appVersionInstance
    }

    def create() {
        respond new AppVersion(params)
    }

    @Transactional
    def save(AppVersion appVersionInstance) {
        if (appVersionInstance == null) {
            notFound()
            return
        }

        if (appVersionInstance.hasErrors()) {
            respond appVersionInstance.errors, view:'create'
            return
        }

        appVersionInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'appVersionInstance.label', default: 'AppVersion'), appVersionInstance.id])
                redirect appVersionInstance
            }
            '*' { respond appVersionInstance, [status: CREATED] }
        }
    }

    def edit(AppVersion appVersionInstance) {
        respond appVersionInstance
    }

    @Transactional
    def update(AppVersion appVersionInstance) {
        if (appVersionInstance == null) {
            notFound()
            return
        }

        if (appVersionInstance.hasErrors()) {
            respond appVersionInstance.errors, view:'edit'
            return
        }

        appVersionInstance.save flush:true

        flash.message = "App Version Updated"
		redirect controller: "admin", action:"index"
    }

    @Transactional
    def delete(AppVersion appVersionInstance) {

        if (appVersionInstance == null) {
            notFound()
            return
        }

        appVersionInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'AppVersion.label', default: 'AppVersion'), appVersionInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'appVersionInstance.label', default: 'AppVersion'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/appVersion/_form.gsp
<%@ page import="com.eximiomedia.AppVersion" %>



<div class="fieldcontain ${hasErrors(bean: appVersionInstance, field: 'appversion', 'error')} ">
	<label for="appversion">
		<g:message code="appVersion.appversion.label" default="Appversion" />
		
	</label>
	<g:textField name="appversion" value="${appVersionInstance?.appversion}" />

</div>

grails-app/views/appVersion/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'appVersion.label', default: 'AppVersion')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-appVersion" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-appVersion" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${appVersionInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${appVersionInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:appVersionInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/appVersion/edit.gsp
<%@ page import="com.eximiomedia.AppVersion" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'appVersion.label', default: 'AppVersion')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-appVersion" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-appVersion" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${appVersionInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${appVersionInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:appVersionInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${appVersionInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/appVersion/index.gsp
<%@ page import="com.eximiomedia.AppVersion" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'appVersion.label', default: 'AppVersion')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-appVersion" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-appVersion" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="appversion" title="${message(code: 'appVersion.appversion.label', default: 'Appversion')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${appVersionInstanceList}" status="i" var="appVersionInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${appVersionInstance.id}">${fieldValue(bean: appVersionInstance, field: "appversion")}</g:link></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${appVersionInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/appVersion/show.gsp
<%@ page import="com.eximiomedia.AppVersion" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'appVersion.label', default: 'AppVersion')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-appVersion" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-appVersion" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list appVersion">
			
				<g:if test="${appVersionInstance?.appversion}">
				<li class="fieldcontain">
					<span id="appversion-label" class="property-label"><g:message code="appVersion.appversion.label" default="Appversion" /></span>
					
						<span class="property-value" aria-labelledby="appversion-label"><g:fieldValue bean="${appVersionInstance}" field="appversion"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:appVersionInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${appVersionInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>